ALTER TABLE employee_leave MODIFY COLUMN `start_date` DATETIME

ALTER TABLE employee_leave MODIFY COLUMN `end_date` DATETIME

DELETE FROM `auth_menu` WHERE id IN (711,717,718,719)
INSERT INTO `auth_menu` (`ID`, `TYPE`, `CODE`, `TITLE`, `URL`, `PRIORITY`, `DESCN`, `PARENT_ID`, `PERM_ID`, `TENANT_ID`, `DISPLAY`, `ICO_TYPE`) VALUES('711','entry','domap','考勤','/domap/map-mapInfoPer-list.do','711',NULL,'13','102',NULL,'true',NULL);
INSERT INTO `auth_menu` (`ID`, `TYPE`, `CODE`, `TITLE`, `URL`, `PRIORITY`, `DESCN`, `PARENT_ID`, `PERM_ID`, `TENANT_ID`, `DISPLAY`, `ICO_TYPE`) VALUES('717','entry','domap','考勤信息管理','/domap/map-mapInfo-list.do','717',NULL,'71','712',NULL,'true',NULL);
INSERT INTO `auth_menu` (`ID`, `TYPE`, `CODE`, `TITLE`, `URL`, `PRIORITY`, `DESCN`, `PARENT_ID`, `PERM_ID`, `TENANT_ID`, `DISPLAY`, `ICO_TYPE`) VALUES('718','entry','domap','考勤规则设置','/domap/map-mapGroup-list.do','718',NULL,'71','712',NULL,'true',NULL);
INSERT INTO `auth_menu` (`ID`, `TYPE`, `CODE`, `TITLE`, `URL`, `PRIORITY`, `DESCN`, `PARENT_ID`, `PERM_ID`, `TENANT_ID`, `DISPLAY`, `ICO_TYPE`) VALUES('719','entry','domap','特殊日期设定','/domap/map-mapHolidays-list.do','719',NULL,'71','712',NULL,'true',NULL);

DROP TABLE IF EXISTS `map_user`;
DROP TABLE IF EXISTS `map_info`;
DROP TABLE IF EXISTS `map_exception`;
DROP TABLE IF EXISTS `map_phone`;
DROP TABLE IF EXISTS `map_group`;
DROP TABLE IF EXISTS `map_holidays`;

CREATE TABLE `map_phone` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT(20) DEFAULT NULL COMMENT '用户名ID',
  `PHONE_NAME` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手机名称',
  `PHONE_ID` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手机唯一ID',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1264049006264321 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `map_group` (
  `GROUP_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `GROUP_NAME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '分组名称',
  `GROUP_CENTER` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '围栏中心点坐标',
  `CENTER_SITE` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '中心点地址名称',
  `RADIUS` INT(20) DEFAULT NULL COMMENT '围栏半径',
  `GTOUP_WEEK` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '考勤日期 周一1 周日7',
  `START_TIME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '上班时间',
  `END_TIME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '下班时间',
  `OVER_TIME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '加班开始时间',
  `ALERT_TIME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '提醒时间',
  PRIMARY KEY (`GROUP_ID`)
) ENGINE=INNODB AUTO_INCREMENT=1264269384876033 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `map_user` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT(20) DEFAULT NULL COMMENT '用户ID',
  `USER_GROUP` BIGINT(20) DEFAULT NULL COMMENT '分组ID',
  PRIMARY KEY (`ID`),
  KEY `FK_MAP_USER_USER_GROUP` (`USER_GROUP`),
  CONSTRAINT `FK_MAP_USER_USER_GROUP` FOREIGN KEY (`USER_GROUP`) REFERENCES `map_group` (`GROUP_ID`)
) ENGINE=INNODB AUTO_INCREMENT=2302 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `map_exception` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT(20) DEFAULT NULL COMMENT '用户ID',
  `CURRENT_TIMES` DATE DEFAULT NULL COMMENT '异常时间',
  `PHONE_STATUS` INT(100) DEFAULT NULL COMMENT '0上午1下午',
  `PHONE_ID` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手机ID',
  `PHONE_NAME` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手机名称',
  `EX_ID` BIGINT(20) DEFAULT NULL COMMENT '异常人(帮助打卡的人)',
  `PHOTO_PATH` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '照片路径',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1264424114601985 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `map_holidays` (
  `MAP_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `MAP_TIME` DATE DEFAULT NULL COMMENT '日期',
  `STATUS` INT(10) DEFAULT NULL COMMENT '是否上班 0休息 1上班',
  `MAP_NOTES` VARCHAR(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`MAP_ID`)
) ENGINE=INNODB AUTO_INCREMENT=1264114335924225 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `map_info` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT(20) DEFAULT NULL COMMENT '用户ID',
  `USER_NAME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户名',
  `DEPARTMENT_ID` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户部门ID',
  `CURRENT_TIMES` DATE DEFAULT NULL COMMENT '签到时间年月日',
  `START_WORK_TIME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '上班时间',
  `START_TIME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '规定上班时间',
  `START_SITE` VARCHAR(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '上班打卡地点',
  `START_OUT` INT(10) DEFAULT '0' COMMENT '上班外勤0本地 1外勤',
  `START_OUT_REASON` VARCHAR(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '上班外勤理由',
  `START_STATUS` INT(10) DEFAULT '0' COMMENT '上班状态0缺卡 1正常 1迟到',
  `START_PHOTO` BIGINT(20) DEFAULT NULL COMMENT '上班照片ID',
  `END_WORK_TIME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '下班时间',
  `END_TIME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '规定下班时间',
  `END_SITE` VARCHAR(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '下班打卡地点',
  `END_OUT` INT(10) DEFAULT '0' COMMENT '下班外勤0本地 1外勤',
  `END_OUT_REASON` VARCHAR(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '下班外勤理由',
  `END_STATUS` INT(10) DEFAULT '0' COMMENT '下班状态0缺卡 1正常 2早退',
  `END_PHOTO` BIGINT(20) DEFAULT NULL COMMENT '下班照片ID',
  `ALL_TIME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '当天上班时间 工时',
  `OVER_TIME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '加班开始时间',
  `OVER_WORK_TIME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '加班时间',
  `CHOOSE` INT(10) DEFAULT '0' COMMENT '0上班1请假(半)2旷工3事假4出差5不上班(休息日加班)',
  `PHONE_ID` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手机类型',
  `GROUP_NAME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '分组名称',
  PRIMARY KEY (`ID`),
  KEY `FK_MAP_INFO_STARTPHONE` (`START_PHOTO`),
  KEY `FK_MAP_INFO_ENDPHONE` (`END_PHOTO`),
  CONSTRAINT `FK_MAP_INFO_ENDPHONE` FOREIGN KEY (`END_PHOTO`) REFERENCES `map_exception` (`ID`),
  CONSTRAINT `FK_MAP_INFO_STARTPHONE` FOREIGN KEY (`START_PHOTO`) REFERENCES `map_exception` (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1264424114864129 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


